### PR TITLE
Add a basic implementation of SSL selfsigned certificates creation and renewal and the missing literature in the OSSL functions tooltips

### PR DESCRIPTION
**Pull request by AdilElFarissi**
+ Add the missing literature in the OSSL functions tooltips.
+ Add a basic implementation to allow a user-friendly automatic selfsigned certificates creation and renewal for local and external use. When enabled, will create a folder SSL\ and 2 sub folders SSL\ssl\ and SSL\src\. Next creates and store an RSA private key in SSL\src\ and the derived selfsigned certificates in SSL\ssl\ folder. Is also possible to renew the certificate on every server restart if CertRenewOnStartup is set to true. (see OpenSim.ini.example [Startup])

Note: The SSL related params in the network section was adapted to be user-friendly and allow the usage just by uncommenting the SSL params in both sections and a password change.

Web Rain :)

### CODE REVIEW

**Comment by UbitUmarov** [comment]
still waiting better days to look

**Comment by AdilElFarissi** [comment]
Hi @UbitUmarov  :)
The recent changes in bin/ScriptSyntax.xml did conflicts and requiere a manual copy/past to fix... there is all the the os functions wiki descriptions in it...
Thank you and good continuation :)

**Comment by AdilElFarissi** [comment]
@UbitUmarov 
ScriptSyntax.xml costed me more than 1 week to do and because the last useless changes, i can't sync my fork with the main... so, i think i will wait the stable release to work on top of it... this will avoid me dramas like this...
Thank you and good continuation :)

**Comment by UbitUmarov** [comment]
dont bother with scripsyntax.xml   i create it with a small program

**Comment by UbitUmarov** [comment]
Relevant commits where added to master. Thanks

**Pull request closed without merging**
